spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

jedis:
  pool:
    host: localhost
    port: 6379
    config:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis: 100000

kafka:
  consumer:
    servers: localhost:9092
    session.timeout: 6000
    group.id: zymtest
    concurrency: 1
    enable.auto.commit: false
    auto:
      commit.interval: 1000
      offset.reset: latest
  producer:
    servers: localhost:9092
    retries: 0
    batch.size: 4096
    linger: 1
    buffer.memory: 40960