spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml



jedis:
  pool:
    host: localhost
    port: 6379
    config:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis: 100000
